# Generated by Django 6.0.2 on 2026-03-09 07:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='available_seats',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='capacity',
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_number',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_type',
            field=models.CharField(choices=[('Train', 'Train'), ('Bus', 'Bus')], max_length=20),
        ),
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coach_name', models.CharField(max_length=10)),
                ('coach_type', models.CharField(choices=[('General', 'General'), ('AC', 'AC'), ('Non-AC', 'Non-AC'), ('Sleeper', 'Sleeper'), ('Sleeper 2 Tier', 'Sleeper 2 Tier'), ('Sleeper 3 Tier', 'Sleeper 3 Tier')], max_length=20)),
                ('total_seats', models.IntegerField()),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.schedule')),
            ],
        ),
    ]
