# Generated by Django 6.0.2 on 2026-03-09 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_remove_schedule_available_seats_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='capacity',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
